### ISSUE TITLE
How can I search this paper ”Few-Shot Keyword Spotting with Prototypical Networks“

### ISSUE THREAD

**Issue by five517** [ArchitParnami/Few-Shot-KWS#1]
I can’t  find this paper，am I search wrong word？

**Comment by ArchitParnami** [comment]
Hello. The paper is still under review and has not been published yet. I will post the link to the paper once we get the reviews.

**Comment by five517** [comment]
Thank you

**Comment by ArchitParnami** [comment]
The paper is now available on Arxiv.org
https://arxiv.org/abs/2007.14463

**Comment by five517** [comment]
thank you so much ！

发自我的 iPhone

在 2020年7月30日，08:47，Archit Parnami <notifications@github.com<mailto:notifications@github.com>> 写道：


The paper is now available on Arxiv.org<http://Arxiv.org>
https://arxiv.org/abs/2007.14463
